name: fastapi-ci-cheap

on:
  push:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'requirements.txt'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'requirements.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    # [skip ci] で手動スキップ可（pushイベントのみ）
    if: github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps (quiet)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test (import only)
        run: python -c "import app; print('import ok')"
